import type {
  TypographerOptions,
  TypographyConfig,
  TypographyOperationId,
} from "./types.js";

export const defaultOperationOrder: readonly TypographyOperationId[] = [
  "normalizeUnicode",
  "symbols",
  "ellipsis",
  "quotes",
  "apostrophes",
  "primeMarks",
  "dashes",
  "minus",
  "punctuationSpacing",
  "whitespace",
  "nbsp",
  "softHyphen",
];

export const typographyDefaults: TypographyConfig = {
  enabled: true,
  locale: "en-US",
  fallbackLocale: "en-US",
  preset: "ui",
  operations: {
    order: defaultOperationOrder,
    normalizeUnicode: true,
    symbols: true,
    ellipsis: true,
    quotes: true,
    apostrophes: true,
    primeMarks: false,
    dashes: true,
    minus: true,
    punctuationSpacing: true,
    whitespace: true,
    nbsp: true,
    softHyphen: false,
  },
  quotes: {
    enabled: true,
    style: "locale-default",
    punctuation: "safe",
    unbalanced: "diagnostic",
  },
  dashes: {
    enabled: true,
    englishEmDashStyle: "no-spaces",
    englishRanges: "en-dash",
    spanishRaya: true,
    spanishRanges: "hyphen",
    minusSign: true,
  },
  spaces: {
    normalizeWhitespace: true,
    nbsp: {
      enabled: true,
      bindShortWords: true,
      bindInitials: true,
      bindTitles: true,
      bindNumbersAndUnits: true,
      bindDates: true,
      bindTimes: true,
      bindCurrency: true,
      useNarrowNbspForThousands: true,
    },
    punctuationSpacing: {
      enabled: true,
      removeSpaceBeforePunctuation: true,
      ensureSpaceAfterPunctuation: true,
    },
  },
  spanish: {
    invertedQuestionMarks: "normalize-existing",
    invertedExclamationMarks: "normalize-existing",
    quoteFinalPeriod: "safe",
  },
  hyphenation: {
    enabled: false,
    hyphenChar: "\u00AD",
    minWordLength: 7,
    exceptions: {},
    skipAllCaps: true,
    skipCapitalizedWords: false,
    skipMixedAlphanumeric: true,
    skipWordsWithDigits: true,
    skipUrls: true,
    skipEmails: true,
    skipHashtags: true,
    skipMentions: true,
    compoundWords: "skip",
  },
  exclusions: {
    tags: [
      "code",
      "pre",
      "kbd",
      "samp",
      "textarea",
      "script",
      "style",
      "math",
      "svg",
    ],
    components: [],
    componentNames: [],
    dataAttribute: {
      name: "data-typography",
      skipValues: ["skip", "off", "false"],
    },
  },
  traversal: {
    customComponents: "process-children",
    fragments: "process",
    portals: "skip",
    textSegmentation: "node",
    processNumbers: false,
    maxDepth: null,
  },
  hyphenators: {},
};

export const typographerDefaults: TypographerOptions = {
  outputMode: "unicode",
  localeFallback: "en-US",
  quotes: {
    normalize: true,
    style: "locale-default",
    movePunctuation: "safe",
  },
  dashes: {
    normalizeHyphenMinus: true,
    englishEmDashStyle: "no-spaces",
    spanishRayaChar: "\u2014",
    normalizeSpanishEnDashToHyphenInRanges: true,
  },
  spaces: {
    useNbsp: true,
    useNarrowNbspForThousands: true,
    bindShortWords: true,
    bindInitials: true,
    bindNumbersAndUnits: true,
  },
  numbers: {
    spanishDecimalSeparator: "preserve",
    englishPercentStyle: "no-space",
    spanishPercentStyle: "space",
    normalizeSpanishThousands: false,
  },
  spanish: {
    insertOpeningPunctuation: "never",
    correctSiglaApostrophePlural: false,
  },
  hyphenation: {
    enabled: false,
    minWordLength: 7,
    skipHeadings: false,
    skipAllCaps: true,
    skipCapitalizedWords: false,
    hyphenateCompoundWords: false,
    remapExistingSoftHyphens: false,
    exceptions: {},
  },
};
